apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-listener
  namespace: development
  labels:
    eventlistener: github-listener
spec:
  serviceAccountName: pipeline
  triggers:
    - name: github-listener
      interceptor:
        ref:
          name: "github" 
          kind: ClusterInterceptor
          apiVersion: triggers.tekton.dev/v1alpha1
        params:
          - name: "secretRef"
            value:
              secretName: github-secret
              secretKey: secretToken
          - name: "eventTypes"
            value: ["pull_request", "push"]
          - name: "addChangedFiles"
            value:
              enabled: true
      bindings:
        - ref: github-pipeline-binding
      template:
        ref: github-pipeline-template 
