name: Trigger Tekton Pipeline

on:
  push:
    branches:
      - main 

jobs:
  trigger-tekton:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Authenticate with Kubernetes
        env:
          PIPELINE_TOKEN: ${{ secrets.PIPELINE_TOKEN }}
        run: |
          kubectl config set-credentials github-actions-sa --token=$PIPELINE_TOKEN
          kubectl config set-cluster development-k8s-cluster --server=https://development-k8s-cluster-dns-edn1s8zb.hcp.southafricanorth.azmk8s.io:443 --insecure-skip-tls-verify=true
          kubectl config set-context development-k8s-cluster --cluster=development-k8s-cluster --user=github-actions-sa
          kubectl config use-context development-k8s-cluster
          kubectl get nodes

      - name: Trigger Tekton Pipeline
        run: |
          kubectl apply -f dsv3-pipeline-run-testt.yaml
